Repository scieloorg/document-store-migracao, pull requests merged in 2019-05, with the labels that each got.

#86 Trata erros do LXML durante a validação de artigos
  documentstore_migracao/processing/validation.py
  tests/test_processing.py
Labels: bug

#89 Adição do tqdm para a Barra de progresso do fluxo de migraçao
  documentstore_migracao/processing/conversion.py
  documentstore_migracao/processing/packing.py
  documentstore_migracao/processing/validation.py
  documentstore_migracao/tools/constructor.py
  documentstore_migracao/tools/generation.py
  documentstore_migracao/utils/logger.py
Labels: v0.2

#127 Adiciona a capacidade de importar os `document renditions`
  documentstore_migracao/processing/inserting.py
  documentstore_migracao/utils/manifest.py
  tests/samples/S0036-36342008000100001/0036-3634-spm-50-01-1-2.xml
  tests/samples/S0036-36342008000100001/a01v50n1.html
  tests/samples/S0036-36342008000100001/a01v50n1.pdf
  tests/test_inserting.py
Labels: enhancement
